insert into Appartement (
    ID, CAPACITY, APPARTEMENT_NAAM, STAD, IS_PARKING_BESCHIKBAAR, AFSTAND_TOT_CENTRUM, EXTRA_INFO, PRIJS_PER_MAAND,
    AANTAL_SLAAPKAMERS, OPPERVLAKTE, HUISDIEREN_TOEGELATEN)
values (
           1, 2, 'testnaam', 'Antwerpen', true, 50, 'info', 500, 3, 30, true);

insert into Appartement (
    ID, CAPACITY, APPARTEMENT_NAAM, STAD, IS_PARKING_BESCHIKBAAR, AFSTAND_TOT_CENTRUM, EXTRA_INFO, PRIJS_PER_MAAND,
    AANTAL_SLAAPKAMERS, OPPERVLAKTE, HUISDIEREN_TOEGELATEN)
values (
           2, 2, 'testnaam1', 'Antwerpen', false, 50, 'info', 300, 3, 30, false);

insert into Appartement (
    ID, CAPACITY, APPARTEMENT_NAAM, STAD, IS_PARKING_BESCHIKBAAR, AFSTAND_TOT_CENTRUM, EXTRA_INFO, PRIJS_PER_MAAND,
    AANTAL_SLAAPKAMERS, OPPERVLAKTE, HUISDIEREN_TOEGELATEN)
values (
           3, 2, 'testnaam2', 'Antwerpen', true, 30, 'info', 500, 2, 30, false);

insert into Appartement (
    ID, CAPACITY, APPARTEMENT_NAAM, STAD, IS_PARKING_BESCHIKBAAR, AFSTAND_TOT_CENTRUM, EXTRA_INFO, PRIJS_PER_MAAND,
    AANTAL_SLAAPKAMERS, OPPERVLAKTE, HUISDIEREN_TOEGELATEN)
values (
           4, 5, 'testnaam3', 'Mechelen', true, 59, 'info', 500, 4, 30, true);

insert into Boeking (
    ID, START_DATUM, EIND_DATUM, NUM_DAYS, NUM_GUESTS, APPARTEMENT_ID)
values (
           1, '2021-04-03', '2021-04-25', 22, 4, 1);