insert into APPARTEMENT (
    ID, CAPACITY, APPARTEMENT_NAAM, STAD, IS_PARKING_BESCHIKBAAR, AFSTAND_TOT_CENTRUM, EXTRA_INFO, PRIJS_PER_MAAND,
                         AANTAL_SLAAPKAMERS, OPPERVLAKTE, HUISDIEREN_TOEGELATEN)
values (
           1, 2, 'testnaam', 'Antwerpen', true, 50, 'info', 500, 3, 30, true);

insert into APPARTEMENT (
    ID, CAPACITY, APPARTEMENT_NAAM, STAD, IS_PARKING_BESCHIKBAAR, AFSTAND_TOT_CENTRUM, EXTRA_INFO, PRIJS_PER_MAAND,
    AANTAL_SLAAPKAMERS, OPPERVLAKTE, HUISDIEREN_TOEGELATEN)
values (
           2, 2, 'testnaam', 'Antwerpen', true, 50, 'info', 500, 3, 30, true);

insert into APPARTEMENT (
    ID, CAPACITY, APPARTEMENT_NAAM, STAD, IS_PARKING_BESCHIKBAAR, AFSTAND_TOT_CENTRUM, EXTRA_INFO, PRIJS_PER_MAAND,
    AANTAL_SLAAPKAMERS, OPPERVLAKTE, HUISDIEREN_TOEGELATEN)
values (
           3, 2, 'testnaam', 'Antwerpen', true, 50, 'info', 500, 3, 30, true);

insert into APPARTEMENT (
    ID, CAPACITY, APPARTEMENT_NAAM, STAD, IS_PARKING_BESCHIKBAAR, AFSTAND_TOT_CENTRUM, EXTRA_INFO, PRIJS_PER_MAAND,
    AANTAL_SLAAPKAMERS, OPPERVLAKTE, HUISDIEREN_TOEGELATEN)
values (
           4, 2, 'testnaam', 'Antwerpen', true, 50, 'info', 500, 3, 30, true);



